### ISSUE TITLE
MySQL DB is locked

### ISSUE THREAD

**Issue by tamimology** [traccar/traccar-docker#106]
I have my Traccar DB into MariaDB. Whenever the host is restarted, I cannot get Traccar to boot up, it is something related to the DB being locked by an old session.

Below is my log for Traccar
```
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 7249574b5437 (172.18.0.8) since 2/21/23, 7:19 PM
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:275)
	at liquibase.Liquibase$18.run(Liquibase.java:2187)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2431)
	at liquibase.Liquibase.clearCheckSums(Liquibase.java:2182)
	at org.traccar.storage.DatabaseModule.provideDataSource(DatabaseModule.java:95)
	at org.traccar.storage.DatabaseModule$$FastClassByGuice$$1804533.GUICE$TRAMPOLINE(<generated>)
	at org.traccar.storage.DatabaseModule$$FastClassByGuice$$1804533.apply(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101)`
```

**And this is my compose for both Traccar anr MariaDB**

```
  traccar:
    container_name: traccar
    restart: always
    volumes:
      - $LOCAL_TIME:/etc/localtime:ro
      - $PERSIST/traccar/logs:/opt/traccar/logs:rw
      - $PERSIST/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro
    ports:
      - 8082:8082
    depends_on: #https://www.traccar.org/mysql/
      - mariadb
    image: 'traccar/traccar:alpine'`

  mariadb:
    container_name: mariadb
    restart: $RESTART_POLICY
    environment:
       - MARIADB_ROOT_PASSWORD=$DB_PASSWORD
       - MARIADB_USER=traccar
       - MARIADB_PASSWORD=$DB_PASSWORD
       - MARIADB_DATABASE=traccar
       - MARIADB_ROOT_HOST=192.168.1.10
       - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
       - PGID=$PGID
       - PUID=$PUID
       - TZ=$TZ
    volumes:
       - $PERSIST/mariadb:/config
       - $LOCAL_TIME:/etc/localtime:ro
mysql --user=[User] --password=[Password] -h[Host] [db_name]<[mysql_file]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
    ports:
      - 3306:3306
    tty: true
    image: 'lscr.io/linuxserver/mariadb:latest'
```

**This is my traccar.xml file**

```xml
<properties>
<entry key="config.default">./conf/default.xml</entry>
<!-- 

    This is the main configuration file. All your configuration parameters should be placed in this file.

    Default configuration parameters are located in the "default.xml" file. You should not modify it to avoid issues
    with upgrading to a new version. Parameters in the main config file override values in the default file. Do not
    remove "config.default" parameter from this file unless you know what you are doing.

    For list of available parameters see following page: https://www.traccar.org/configuration-file/

<!--  MariaDB-MySQL  -->
<!--  <entry key='database.driver'>com.mysql.jdbc.Driver</entry>  -->
<entry key="database.driver">com.mysql.cj.jdbc.Driver</entry>
<entry key="database.url">jdbc:mysql://mariadb:3306/traccar?serverTimezone=Australia/Melbourne&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=''</entry>
<entry key="database.user">traccar</entry>
<entry key="database.password">1234ABCD</entry>
<!--  GeoCoder  -->
<entry key="geocoder.enable">true</entry>
<entry key="geocoder.type">nominatim</entry>
<entry key="geocoder.url">http://188.40.20.228/nominatim/reverse.php</entry>
<entry key="geocoder.format">%r, %h, %u, %t - %s</entry>
</properties>
```

**Comment by tananaev** [comment]
You need to remove lock from your database. Check our forum. It has been discussed many times.
