### ISSUE TITLE
With v5.0: java.util.zip.ZipException: invalid entry CRC

### ISSUE THREAD

**Issue by scradster** [traccar/traccar-docker#89]
Hi

Thanks for the awesome project!

When I try to start v5.0 I get the following error:

```
[+] Running 4/4
 ⠿ traccar Pulled                                                                                                                                                                                              8.9s
   ⠿ df9b9388f04a Already exists                                                                                                                                                                               0.0s
   ⠿ 439c5aa8b3c7 Pull complete                                                                                                                                                                                0.6s
   ⠿ cacfe428443a Pull complete                                                                                                                                                                                7.0s
[+] Running 2/2
 ⠿ Network traccar_default      Created                                                                                                                                                                        0.1s
 ⠿ Container traccar-traccar-1  Created                                                                                                                                                                        0.3s
Attaching to traccar-traccar-1
traccar-traccar-1  | java.util.zip.ZipException: invalid entry CRC (expected 0xa1999cf7 but got 0x5532a62e)
traccar-traccar-1  |    at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:224)
traccar-traccar-1  |    at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:143)
traccar-traccar-1  |    at org.h2.util.Utils.loadResource(Utils.java:420)
traccar-traccar-1  |    at org.h2.util.Utils.getResource(Utils.java:386)
traccar-traccar-1  |    at org.h2.message.DbException.<clinit>(DbException.java:74)
traccar-traccar-1  |    at org.h2.message.TraceObject.<clinit>(TraceObject.java:108)
traccar-traccar-1  |    at org.h2.Driver.connect(Driver.java:59)
traccar-traccar-1  |    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
traccar-traccar-1  |    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
traccar-traccar-1  |    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
traccar-traccar-1  |    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
traccar-traccar-1  |    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
traccar-traccar-1  |    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
traccar-traccar-1  |    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
traccar-traccar-1  |    at org.traccar.database.DataManager.initDatabase(DataManager.java:120)
traccar-traccar-1  |    at org.traccar.database.DataManager.<init>(DataManager.java:79)
traccar-traccar-1  |    at org.traccar.Context.init(Context.java:307)
traccar-traccar-1  |    at org.traccar.Main.run(Main.java:113)
traccar-traccar-1  |    at org.traccar.Main.main(Main.java:107)
```

My docker-compose.yml:

```
services:
  traccar:
    image: traccar/traccar:latest
    ports:
      - 172.17.0.1:8082:8082
    volumes:
      - ./logs:/opt/traccar/logs
      - ./traccar.xml:/opt/traccar/conf/traccar.xml
      - ./data:/opt/traccar/data
    restart: always
```

When I change to `image: traccar/traccar:4.15` everything works well.

Any ideas?

Thanks

**Comment by scradster** [comment]
Nevermind, if I use the correct image name (`traccar/traccar:debian`) everything is working fine :)
/close
